apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
spec:
  selector:
    matchLabels:
      components: {{ .Values.api.components }}
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
        components: {{ .Values.api.components }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image }}:{{ .Values.api.version }}"
          ports:
            - containerPort: {{ .Values.api.port }}
          resources:
            limits: {{ .Values.api.limits | toYaml | nindent 14 }}
          env:
            {{- range .Values.api.envs }}
            {{- $data := dict "name" $.Values.rabbitmq.name "env" . }}
            {{- include "env.template" $data | indent 12 }}
            {{- end }}
          volumeMounts:
            - mountPath: /opt/app/uploads
              name: {{ .Values.api.name }}-data
      volumes:
        - name: {{ .Values.api.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.api.name }}-pvc