apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}
  labels:
    app: {{ .Values.rabbitmq.app }}
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.ports.aqmp }}
      targetPort: {{ .Values.rabbitmq.ports.aqmp }}
      protocol: TCP
    - name: management
      port: {{ .Values.rabbitmq.ports.managment }}
      targetPort: {{ .Values.rabbitmq.ports.managment }}
      protocol: TCP
  selector:
    app: {{ .Values.rabbitmq.app }}