apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.name }}-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.database.RABBITMQ_DEFAULT_USER | b64enc }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.database.RABBITMQ_DEFAULT_PASS | b64enc }}
  AMQP_EXCHANGE: {{ .Values.database.AMQP_EXCHANGE | b64enc }}
  AMQP_USER: {{ .Values.database.AMQP_USER | b64enc }}
  AMQP_PASSWORD: {{ .Values.database.AMQP_PASSWORD | b64enc }}
  AMQP_HOSTNAME: {{ .Values.database.AMQP_HOSTNAME | b64enc}}
  AMQP_QUEUE: {{ .Values.database.AMQP_QUEUE | b64enc }}