apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.rabbitmq.name }}-pvc
spec:
  resources:
    requests:
      storage: {{ .Values.rabbitmq.storage }}
  accessModes:
    - ReadWriteOnce