apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-service-deployment
spec:
  selector:
    matchLabels:
      components: service
  replicas: 1
  template:
    metadata:
      labels:
        components: service
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-service:1.0
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  key: AMQP_EXCHANGE
                  name: rabbitmq-secret
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  key: AMQP_USER
                  name: rabbitmq-secret
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: AMQP_PASSWORD
                  name: rabbitmq-secret
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  key: AMQP_HOSTNAME
                  name: rabbitmq-secret
            - name: AMQP_QUEUE
              valueFrom:
                secretKeyRef:
                  key: AMQP_QUEUE
                  name: rabbitmq-secret
