apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-app
spec:
  replicas: 1
  selector:
    matchLabels:
      components: frontend
  template:
    metadata:
      labels:
        components: frontend
    spec:
      containers:
        - name: conv-app
          image: antonlarichev/conv-app:1.2
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "500Mi"
              cpu: "300m"
          env:
            - name: VITE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: conv-app-configmap
                  key: VITE_DOMAIN