apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api
spec:
  selector:
    matchLabels:
      components: backend
  replicas: 1
  template:
    metadata:
      labels:
        components: backend
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api:1.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  key: AMQP_EXCHANGE
                  name: rabbitmq-secret
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  key: AMQP_USER
                  name: rabbitmq-secret
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: AMQP_PASSWORD
                  name: rabbitmq-secret
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  key: AMQP_HOSTNAME
                  name: rabbitmq-secret
          volumeMounts:
            - mountPath: /opt/app/uploads
              name: conv-api-data
      volumes:
        - name: conv-api-data
          persistentVolumeClaim:
            claimName: api-pvc