apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-api
  labels:
    app: conv-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conv-api
  template:
    metadata:
      labels:
        app: conv-api
    spec:
      containers:
        - name: conv-api
          image: antonlarichev/conv-api:1.0
          ports:
            - containerPort: 3000
          env:
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_PASSWORD
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: AMQP_HOSTNAME
          resources:
            limits:
              memory: "800Mi"
              cpu: "500m"
          volumeMounts:
            - name: api-pvc-test
              mountPath: /opt/app/uploads
      volumes:
        - name: api-pvc-test
          persistentVolumeClaim:
            claimName: api-pvc